version: '3.8'

services:
  web:
    image: nginx:alpine
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example.rule=Host(`example.cryptotel.xyz`)"
      - "traefik.http.routers.example.entrypoints=websecure"
      - "traefik.http.routers.example.tls=true"
      - "traefik.http.routers.example.tls.certresolver=selfsigned"
      - "traefik.http.services.example.loadbalancer.server.port=80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  traefik:
    external: true 