global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.cryptotel.xyz:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor.cryptotel.xyz:8080']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik.cryptotel.xyz:8080']
    metrics_path: /metrics

  - job_name: 'portainer'
    static_configs:
      - targets: ['portainer.cryptotel.xyz:9000']
    metrics_path: /api/endpoints/1/docker/containers/json

  - job_name: 'docker-swarm'
    static_configs:
      - targets: ['localhost:9323']
    metrics_path: /metrics

  - job_name: 'registry'
    static_configs:
      - targets: ['registry.cryptotel.xyz:5000']
    metrics_path: /metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana.cryptotel.xyz:3000']
    metrics_path: /metrics

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager.cryptotel.xyz:9093']
    metrics_path: /metrics 