version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock --admin-password-file /admin_password.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./admin_password.txt:/admin_password.txt:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.cryptotel.xyz`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=selfsigned"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - traefik
volumes:
  portainer_data:
networks:
  traefik:
    external: true 